-- ============================================================
-- FawryBook Database Schema — Oracle DDL Migration Script
-- ============================================================
-- This file can be run manually against an Oracle database to create
-- all required tables, constraints, and indexes.
--
-- Why a manual schema.sql (not relying on Hibernate ddl-auto=update):
-- 1. Reproducible: exact same schema on every environment
-- 2. Reviewable: DBA can inspect before running in production
-- 3. Deliverable: the task requires migration scripts
-- 4. Safer: ddl-auto=update can't drop columns, rename fields, or add complex constraints
--
-- Oracle-specific notes:
-- - GENERATED BY DEFAULT AS IDENTITY: Oracle 12c+ auto-increment (maps to JPA GenerationType.IDENTITY)
-- - CLOB: for large text content (Oracle VARCHAR2 max = 4000 bytes)
-- - TIMESTAMP: Oracle's equivalent of LocalDateTime
-- ============================================================

-- ==================== 1. USERS TABLE ====================
-- Why "users" (not "user"): "USER" is a reserved word in Oracle SQL
CREATE TABLE users (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(255)  NOT NULL,
    last_name   VARCHAR2(255)  NOT NULL,
    email       VARCHAR2(255)  NOT NULL,
    password    VARCHAR2(255)  NOT NULL,
    country     VARCHAR2(255),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Why unique index on email:
-- 1. Enforces no duplicate accounts at the DB level (defense in depth beyond app validation)
-- 2. Speeds up login lookups (findByEmail) — email is the primary query key for auth
CREATE UNIQUE INDEX idx_users_email ON users (email);


-- ==================== 2. POSTS TABLE ====================
CREATE TABLE posts (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(255)  NOT NULL,
    content     CLOB           NOT NULL,
    author_id   NUMBER         NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- ==================== 3. POST_TAGS TABLE ====================
-- Why a separate table (not a comma-separated string in posts):
-- JPA @ElementCollection maps tags to this join table automatically
-- This allows proper SQL queries like "find all posts with tag X" using WHERE tag = 'X'
CREATE TABLE post_tags (
    post_id  NUMBER        NOT NULL,
    tag      VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_post_tags_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
);


-- ==================== 4. COMMENTS TABLE ====================
CREATE TABLE comments (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     CLOB    NOT NULL,
    author_id   NUMBER  NOT NULL,
    post_id     NUMBER  NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_comments_post   FOREIGN KEY (post_id)   REFERENCES posts (id) ON DELETE CASCADE
);

-- ==================== 5. REACTIONS TABLE ====================
CREATE TABLE reactions (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type     VARCHAR2(10) NOT NULL,
    user_id  NUMBER       NOT NULL,
    post_id  NUMBER       NOT NULL,
    CONSTRAINT fk_reactions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reactions_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    -- Why CHECK constraint: ensures only valid enum values are stored — defense in depth
    CONSTRAINT chk_reaction_type CHECK (type IN ('LIKE', 'DISLIKE'))
);

-- Why unique constraint on (user_id, post_id):
-- Enforces "one reaction per user per post" at the DB level
-- Prevents race conditions where a user could submit multiple likes simultaneously
CREATE UNIQUE INDEX uk_reaction_user_post ON reactions (user_id, post_id);
